import { GEO_CITIES } from '@/lib/geo-seo-cities';

/** English geoip / MaxMind city names → Turkish display labels (client-safe). */
export const ANALYTICS_CITY_EN_TO_TR: Record<string, string> = {
  ...Object.fromEntries(GEO_CITIES.map((c) => [c.name.toLowerCase(), c.nameTr])),
  bursa: 'Bursa',
  adana: 'Adana',
  gaziantep: 'Gaziantep',
  konya: 'Konya',
  mersin: 'Mersin',
  diyarbakir: 'Diyarbakır',
  diyarbakır: 'Diyarbakır',
  kayseri: 'Kayseri',
  eskisehir: 'Eskişehir',
  eskişehir: 'Eskişehir',
  samsun: 'Samsun',
  denizli: 'Denizli',
  şanlıurfa: 'Şanlıurfa',
  sanliurfa: 'Şanlıurfa',
  malatya: 'Malatya',
  kahramanmaras: 'Kahramanmaraş',
  kahramanmaraş: 'Kahramanmaraş',
  erzurum: 'Erzurum',
  van: 'Van',
  batman: 'Batman',
  elazig: 'Elazığ',
  elazığ: 'Elazığ',
  izmit: 'İzmit',
  gebze: 'Gebze',
  bodrum: 'Bodrum',
  alanya: 'Alanya',
  trabzon: 'Trabzon',
  manisa: 'Manisa',
  balikesir: 'Balıkesir',
  balıkesir: 'Balıkesir',
  aydin: 'Aydın',
  aydın: 'Aydın',
  tekirdag: 'Tekirdağ',
  tekirdağ: 'Tekirdağ',
  sakarya: 'Sakarya',
  mugla: 'Muğla',
  muğla: 'Muğla',
  kutahya: 'Kütahya',
  kütahya: 'Kütahya',
  usak: 'Uşak',
  uşak: 'Uşak',
  dusseldorf: 'Düsseldorf',
  düsseldorf: 'Düsseldorf',
  köln: 'Köln',
  cologne: 'Köln',
  münchen: 'Münih',
  frankfurt: 'Frankfurt',
  hamburg: 'Hamburg',
  rome: 'Roma',
  milan: 'Milano',
  naples: 'Napoli',
  barcelona: 'Barselona',
  valencia: 'Valensiya',
  brussels: 'Brüksel',
  vienna: 'Viyana',
  warsaw: 'Varşova',
  prague: 'Prag',
  budapest: 'Budapeşte',
  athens: 'Atina',
  cairo: 'Kahire',
  jeddah: 'Cidde',
  doha: 'Doha',
  kuwait: 'Kuveyt',
  'kuwait city': 'Kuveyt',
  bangkok: 'Bangkok',
  jakarta: 'Cakarta',
  kuala: 'Kuala Lumpur',
  'kuala lumpur': 'Kuala Lumpur',
  'hong kong': 'Hong Kong',
  shanghai: 'Şangay',
  beijing: 'Pekin',
  seoul: 'Seul',
  tokyo: 'Tokyo',
  osaka: 'Osaka',
  melbourne: 'Melbourne',
  brisbane: 'Brisbane',
  vancouver: 'Vancouver',
  montreal: 'Montreal',
  'sao paulo': 'São Paulo',
  'são paulo': 'São Paulo',
  'mexico city': 'Meksika',
  'buenos aires': 'Buenos Aires',
};

const GEO_CITY_DE: Record<string, string> = {
  istanbul: 'Istanbul',
  ankara: 'Ankara',
  izmir: 'Izmir',
  antalya: 'Antalya',
  london: 'London',
  'new-york': 'New York',
  'los-angeles': 'Los Angeles',
  chicago: 'Chicago',
  dubai: 'Dubai',
  riyadh: 'Riad',
  berlin: 'Berlin',
  munich: 'München',
  paris: 'Paris',
  amsterdam: 'Amsterdam',
  mumbai: 'Mumbai',
  delhi: 'Delhi',
  singapore: 'Singapur',
  sydney: 'Sydney',
  toronto: 'Toronto',
  madrid: 'Madrid',
};

const GEO_CITY_ES: Record<string, string> = {
  istanbul: 'Estambul',
  ankara: 'Ankara',
  izmir: 'Esmirna',
  antalya: 'Antalya',
  london: 'Londres',
  'new-york': 'Nueva York',
  'los-angeles': 'Los Ángeles',
  chicago: 'Chicago',
  dubai: 'Dubái',
  riyadh: 'Riad',
  berlin: 'Berlín',
  munich: 'Múnich',
  paris: 'París',
  amsterdam: 'Ámsterdam',
  mumbai: 'Bombay',
  delhi: 'Delhi',
  singapore: 'Singapur',
  sydney: 'Sídney',
  toronto: 'Toronto',
  madrid: 'Madrid',
};

/** English geoip city names → German display labels. */
export const ANALYTICS_CITY_EN_TO_DE: Record<string, string> = {
  ...Object.fromEntries(
    GEO_CITIES.map((c) => [c.name.toLowerCase(), GEO_CITY_DE[c.slug] ?? c.name]),
  ),
  cologne: 'Köln',
  köln: 'Köln',
  dusseldorf: 'Düsseldorf',
  düsseldorf: 'Düsseldorf',
  munich: 'München',
  münchen: 'München',
  rome: 'Rom',
  milan: 'Mailand',
  naples: 'Neapel',
  barcelona: 'Barcelona',
  brussels: 'Brüssel',
  vienna: 'Wien',
  warsaw: 'Warschau',
  prague: 'Prag',
  budapest: 'Budapest',
  athens: 'Athen',
  cairo: 'Kairo',
  jeddah: 'Dschidda',
  shanghai: 'Shanghai',
  beijing: 'Peking',
  seoul: 'Seoul',
  'sao paulo': 'São Paulo',
  'são paulo': 'São Paulo',
  'mexico city': 'Mexiko-Stadt',
};

/** English geoip city names → Spanish display labels. */
export const ANALYTICS_CITY_EN_TO_ES: Record<string, string> = {
  ...Object.fromEntries(
    GEO_CITIES.map((c) => [c.name.toLowerCase(), GEO_CITY_ES[c.slug] ?? c.name]),
  ),
  cologne: 'Colonia',
  köln: 'Colonia',
  dusseldorf: 'Düsseldorf',
  düsseldorf: 'Düsseldorf',
  munich: 'Múnich',
  münchen: 'Múnich',
  rome: 'Roma',
  milan: 'Milán',
  naples: 'Nápoles',
  barcelona: 'Barcelona',
  brussels: 'Bruselas',
  vienna: 'Viena',
  warsaw: 'Varsovia',
  prague: 'Praga',
  budapest: 'Budapest',
  athens: 'Atenas',
  cairo: 'El Cairo',
  jeddah: 'Yeda',
  shanghai: 'Shanghái',
  beijing: 'Pekín',
  seoul: 'Seúl',
  'sao paulo': 'São Paulo',
  'são paulo': 'São Paulo',
  'mexico city': 'Ciudad de México',
};
