import { GEO_CITIES } from '@/lib/geo-seo-cities';

/** English geoip / MaxMind city names → Turkish display labels (client-safe). */
export const ANALYTICS_CITY_EN_TO_TR: Record<string, string> = {
  ...Object.fromEntries(GEO_CITIES.map((c) => [c.name.toLowerCase(), c.nameTr])),
  bursa: 'Bursa',
  adana: 'Adana',
  gaziantep: 'Gaziantep',
  konya: 'Konya',
  mersin: 'Mersin',
  diyarbakir: 'Diyarbakır',
  diyarbakır: 'Diyarbakır',
  kayseri: 'Kayseri',
  eskisehir: 'Eskişehir',
  eskişehir: 'Eskişehir',
  samsun: 'Samsun',
  denizli: 'Denizli',
  şanlıurfa: 'Şanlıurfa',
  sanliurfa: 'Şanlıurfa',
  malatya: 'Malatya',
  kahramanmaras: 'Kahramanmaraş',
  kahramanmaraş: 'Kahramanmaraş',
  erzurum: 'Erzurum',
  van: 'Van',
  batman: 'Batman',
  elazig: 'Elazığ',
  elazığ: 'Elazığ',
  izmit: 'İzmit',
  gebze: 'Gebze',
  bodrum: 'Bodrum',
  alanya: 'Alanya',
  trabzon: 'Trabzon',
  manisa: 'Manisa',
  balikesir: 'Balıkesir',
  balıkesir: 'Balıkesir',
  aydin: 'Aydın',
  aydın: 'Aydın',
  tekirdag: 'Tekirdağ',
  tekirdağ: 'Tekirdağ',
  sakarya: 'Sakarya',
  mugla: 'Muğla',
  muğla: 'Muğla',
  kutahya: 'Kütahya',
  kütahya: 'Kütahya',
  usak: 'Uşak',
  uşak: 'Uşak',
  dusseldorf: 'Düsseldorf',
  düsseldorf: 'Düsseldorf',
  köln: 'Köln',
  cologne: 'Köln',
  münchen: 'Münih',
  frankfurt: 'Frankfurt',
  hamburg: 'Hamburg',
  rome: 'Roma',
  milan: 'Milano',
  naples: 'Napoli',
  barcelona: 'Barselona',
  valencia: 'Valensiya',
  brussels: 'Brüksel',
  vienna: 'Viyana',
  warsaw: 'Varşova',
  prague: 'Prag',
  budapest: 'Budapeşte',
  athens: 'Atina',
  cairo: 'Kahire',
  jeddah: 'Cidde',
  doha: 'Doha',
  kuwait: 'Kuveyt',
  'kuwait city': 'Kuveyt',
  bangkok: 'Bangkok',
  jakarta: 'Cakarta',
  kuala: 'Kuala Lumpur',
  'kuala lumpur': 'Kuala Lumpur',
  'hong kong': 'Hong Kong',
  shanghai: 'Şangay',
  beijing: 'Pekin',
  seoul: 'Seul',
  tokyo: 'Tokyo',
  osaka: 'Osaka',
  melbourne: 'Melbourne',
  brisbane: 'Brisbane',
  vancouver: 'Vancouver',
  montreal: 'Montreal',
  'sao paulo': 'São Paulo',
  'são paulo': 'São Paulo',
  'mexico city': 'Meksika',
  'buenos aires': 'Buenos Aires',
};
