import type { IndustryTemplate } from '@/lib/industry-templates';

/** Shared archetype templates for Faz D — remaining solution verticals */
export const ARCHETYPE_INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: 'campus-institution',
    name: 'Campus & Institution',
    category: 'url',
    tagline: 'Maps, services and public info — one scan per location',
    description: 'Universities, colleges and government facilities.',
    useCases: ['Building placard', 'Orientation', 'Citizen services', 'Department lobby'],
    suggestedQrName: 'Campus Services',
    qrData: { url: 'https://yoursite.com/info', _orgName: '', _department: '' },
    style: {
      fgColor: '#1e3a8a',
      bgColor: '#eff6ff',
      dotStyle: 'classy',
      cornerStyle: 'classy',
      frameStyle: 'badge',
      frameColor: '#1e3a8a',
      frameText: 'LEARN MORE',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'link',
        title: 'Destination',
        description: 'Portal, map or service page.',
        fields: [
          { key: 'url', label: 'URL', placeholder: 'https://campus.edu/services', required: true, type: 'url' },
        ],
      },
      {
        id: 'org',
        title: 'Organization',
        description: 'Shown on landing page.',
        fields: [
          { key: '_orgName', label: 'Institution name', placeholder: 'State University', type: 'text' },
          { key: '_department', label: 'Department / office', placeholder: 'Student Affairs', type: 'text' },
        ],
      },
    ],
    tips: ['Bulk CSV for hundreds of room placards.', 'Multilingual routing for international users.'],
    landingPage: { enabled: true, template: 'business', title: 'Campus Services', accentColor: '#1e3a8a', ctaLabel: 'Continue' },
  },
  {
    id: 'professional-services',
    name: 'Professional Services',
    category: 'url',
    tagline: 'Client intake and secure portals — law, insurance, accounting',
    description: 'Firms that need intake forms and document uploads.',
    useCases: ['Office lobby', 'Business card', 'Mailer insert', 'Conference booth'],
    suggestedQrName: 'Client Portal',
    qrData: { url: 'https://yourfirm.com/intake', _firmName: '', _practiceArea: '' },
    style: {
      fgColor: '#0f172a',
      bgColor: '#ffffff',
      dotStyle: 'classy',
      cornerStyle: 'classy',
      frameStyle: 'double',
      frameColor: '#0f172a',
      frameText: 'CONTACT US',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'portal',
        title: 'Client destination',
        description: 'Intake form or secure document portal.',
        fields: [
          { key: 'url', label: 'Portal URL', placeholder: 'https://yourfirm.com/intake', required: true, type: 'url' },
        ],
      },
      {
        id: 'firm',
        title: 'Firm details',
        description: 'Shown on landing page and print collateral.',
        fields: [
          { key: '_firmName', label: 'Firm name', type: 'text' },
          { key: '_practiceArea', label: 'Practice area', placeholder: 'Tax · Litigation · P&C', type: 'text' },
        ],
      },
    ],
    tips: ['Password-protect sensitive document links.', 'Never put PII in the QR URL itself.'],
    landingPage: { enabled: true, template: 'business', title: 'Client Services', accentColor: '#0f172a', ctaLabel: 'Get Started' },
  },
  {
    id: 'retail-grocery',
    name: 'Retail & Grocery',
    category: 'url',
    tagline: 'Shelf promos, loyalty and weekly deals',
    description: 'Supermarkets, markets, florists and bakeries.',
    useCases: ['Shelf talker', 'Entrance sign', 'Product tag', 'Loyalty poster'],
    suggestedQrName: 'Weekly Specials',
    qrData: { url: 'https://yourstore.com/deals', _storeName: '', _promo: '' },
    style: {
      fgColor: '#7c3aed',
      bgColor: '#faf5ff',
      dotStyle: 'rounded',
      frameStyle: 'sticker',
      frameColor: '#7c3aed',
      frameText: 'SHOP NOW',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'promo',
        title: 'Promo link',
        description: 'Weekly deals, loyalty signup or product promo.',
        fields: [
          { key: 'url', label: 'Deals URL', required: true, type: 'url' },
          { key: '_storeName', label: 'Store name', type: 'text' },
          { key: '_promo', label: 'Campaign', placeholder: 'Weekly produce sale', type: 'text' },
        ],
      },
    ],
    tips: ['Update Monday promos without reprinting.', 'UTM per store location.'],
    landingPage: { enabled: true, template: 'minimal', title: 'This Week\'s Deals', accentColor: '#7c3aed', ctaLabel: 'View Offers' },
  },
  {
    id: 'entertainment-venue',
    name: 'Entertainment Venue',
    category: 'url',
    tagline: 'Tickets, showtimes and merch from one poster',
    description: 'Cinemas, breweries, music venues and wineries.',
    useCases: ['Lobby poster', 'Tap handle', 'Event wristband', 'Table tent'],
    suggestedQrName: 'Tickets & Events',
    qrData: { url: 'https://yourvenue.com/tickets', _venueName: '', _event: '' },
    style: {
      fgColor: '#7c2d12',
      bgColor: '#fff7ed',
      dotStyle: 'rounded',
      frameStyle: 'scan-me',
      frameColor: '#7c2d12',
      frameText: 'GET TICKETS',
      gradientEnabled: true,
      gradientColor2: '#ea580c',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'tickets',
        title: 'Ticketing',
        description: 'Ticket sales, showtimes or event registration.',
        fields: [
          { key: 'url', label: 'Tickets URL', required: true, type: 'url' },
          { key: '_venueName', label: 'Venue name', type: 'text' },
          { key: '_event', label: 'Show / release', type: 'text' },
        ],
      },
    ],
    tips: ['Swap show URLs between events — same printed poster QR.'],
    landingPage: { enabled: true, template: 'event', title: 'Get Tickets', accentColor: '#7c2d12', ctaLabel: 'Buy Now' },
  },
  {
    id: 'automotive-marine',
    name: 'Automotive & Marine',
    category: 'url',
    tagline: 'Inventory, service lane and marina slips',
    description: 'Dealerships, car wash and boating facilities.',
    useCases: ['Window sticker', 'Service lane', 'Marina dock', 'Detailing bay'],
    suggestedQrName: 'View Inventory',
    qrData: { url: 'https://yourlot.com/inventory', _businessName: '', _stockInfo: '', _servicePromo: '', _agentPhone: '' },
    style: {
      fgColor: '#1d4ed8',
      bgColor: '#eff6ff',
      dotStyle: 'square',
      frameStyle: 'scan-me',
      frameColor: '#1d4ed8',
      frameText: 'VIEW DETAILS',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'listing',
        title: 'Vehicle or service link',
        description: 'Inventory page, VDP or service booking.',
        fields: [
          { key: 'url', label: 'Listing / booking URL', placeholder: 'https://yourlot.com/inventory', required: true, type: 'url' },
        ],
      },
      {
        id: 'business',
        title: 'Business details',
        description: 'Shown on the landing page and print collateral.',
        fields: [
          { key: '_businessName', label: 'Dealership / marina', placeholder: 'Coastal Auto & Marine', type: 'text' },
          { key: '_stockInfo', label: 'Stock / model info', placeholder: '2024 models · 45 in stock', type: 'text' },
          { key: '_servicePromo', label: 'Service offer', placeholder: 'Free multi-point inspection', type: 'text' },
          { key: '_agentPhone', label: 'Sales / service phone', placeholder: '+90 532 ...', type: 'phone' },
        ],
      },
    ],
    tips: ['Geofence per lot location.', 'Update VDP links when inventory turns.', 'Per-salesperson QR for lead attribution.'],
    landingPage: {
      enabled: true,
      template: 'business',
      title: 'Details & Booking',
      accentColor: '#1d4ed8',
      ctaLabel: 'Continue',
      leadFormEnabled: true,
      leadForm: { collectName: true, collectPhone: true, requiredEmail: false },
    },
  },
  {
    id: 'property-facilities',
    name: 'Property & Facilities',
    category: 'url',
    tagline: 'Tenant portals, coworking and warehouse ops',
    description: 'Property management, flex offices and logistics.',
    useCases: ['Building lobby', 'Dock door', 'Member desk', 'Unit mailer'],
    suggestedQrName: 'Building Portal',
    qrData: { url: 'https://yourproperty.com/portal', _buildingName: '', _unitInfo: '', _managerContact: '', _maintenanceUrl: '' },
    style: {
      fgColor: '#166534',
      bgColor: '#f0fdf4',
      dotStyle: 'rounded',
      frameStyle: 'badge',
      frameColor: '#166534',
      frameText: 'TENANT INFO',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'portal',
        title: 'Portal link',
        description: 'Tenant, member or warehouse operations portal.',
        fields: [
          { key: 'url', label: 'Portal URL', placeholder: 'https://yourproperty.com/portal', required: true, type: 'url' },
        ],
      },
      {
        id: 'building',
        title: 'Building details',
        description: 'Shown on the landing page for tenants and members.',
        fields: [
          { key: '_buildingName', label: 'Building / site', placeholder: 'Harbor Point Tower', type: 'text' },
          { key: '_unitInfo', label: 'Unit / floor info', placeholder: 'Floors 1–12 · 240 units', type: 'text' },
          { key: '_managerContact', label: 'Management contact', placeholder: '+90 212 ... / office hours', type: 'text' },
          { key: '_maintenanceUrl', label: 'Maintenance request URL', placeholder: 'https://yourproperty.com/maintenance', type: 'url' },
        ],
      },
    ],
    tips: ['Per-building folders in dashboard.', 'Webhook to maintenance ticketing.', 'Separate QR for tenants vs visitors.'],
    landingPage: { enabled: true, template: 'business', title: 'Building Services', accentColor: '#166534', ctaLabel: 'Open Portal' },
  },
  {
    id: 'specialty-healthcare',
    name: 'Specialty Healthcare',
    category: 'url',
    tagline: 'Vet, optometry and specialty clinic intake',
    description: 'Patient or pet intake and booking flows.',
    useCases: ['Reception poster', 'Appointment card', 'Waiting room'],
    suggestedQrName: 'Patient Intake',
    qrData: { url: 'https://yourclinic.com/intake', _clinicName: '', _specialty: '', _bookingPhone: '', _hours: '' },
    style: {
      fgColor: '#0891b2',
      bgColor: '#ecfeff',
      dotStyle: 'rounded',
      frameStyle: 'badge',
      frameColor: '#0891b2',
      frameText: 'PATIENT CARE',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'intake',
        title: 'Intake destination',
        description: 'Patient or pet intake and appointment booking.',
        fields: [
          { key: 'url', label: 'Intake URL', placeholder: 'https://yourclinic.com/intake', required: true, type: 'url' },
        ],
      },
      {
        id: 'clinic',
        title: 'Clinic details',
        description: 'Shown on the landing page — never encode PHI in the QR link.',
        fields: [
          { key: '_clinicName', label: 'Clinic name', placeholder: 'Bright Eyes Optometry', type: 'text' },
          { key: '_specialty', label: 'Specialty', placeholder: 'Veterinary · Optometry · Dermatology', type: 'text' },
          { key: '_bookingPhone', label: 'Booking phone', placeholder: '+90 532 ...', type: 'phone' },
          { key: '_hours', label: 'Hours', placeholder: 'Mon–Fri 9:00–18:00', type: 'text' },
        ],
      },
    ],
    tips: ['Link to compliant portal — no PHI in QR URL.', 'Separate QR per department for triage analytics.'],
    landingPage: { enabled: true, template: 'business', title: 'Patient Resources', accentColor: '#0891b2', ctaLabel: 'Continue' },
  },
  {
    id: 'family-community',
    name: 'Family & Community',
    category: 'url',
    tagline: 'Enrollment, family portals and faith community',
    description: 'Childcare, senior living and churches.',
    useCases: ['Lobby sign', 'Bulletin insert', 'Family mailer', 'Event poster'],
    suggestedQrName: 'Community Portal',
    qrData: { url: 'https://yourorg.com/portal', _orgName: '', _programType: '', _scheduleInfo: '', _contactInfo: '' },
    style: {
      fgColor: '#9333ea',
      bgColor: '#faf5ff',
      dotStyle: 'extra-rounded',
      frameStyle: 'rounded',
      frameColor: '#9333ea',
      frameText: 'JOIN US',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'community',
        title: 'Community link',
        description: 'Enrollment, family portal or faith community hub.',
        fields: [
          { key: 'url', label: 'Portal URL', placeholder: 'https://yourorg.com/portal', required: true, type: 'url' },
        ],
      },
      {
        id: 'org',
        title: 'Organization details',
        description: 'Shown on the landing page for families and members.',
        fields: [
          { key: '_orgName', label: 'Organization', placeholder: 'Sunshine Childcare', type: 'text' },
          { key: '_programType', label: 'Program type', placeholder: 'Childcare · Senior living · Faith community', type: 'text' },
          { key: '_scheduleInfo', label: 'Schedule / hours', placeholder: 'Services Sun 10:00 · Office Mon–Fri', type: 'text' },
          { key: '_contactInfo', label: 'Contact', placeholder: '+90 212 ... / info@yourorg.com', type: 'text' },
        ],
      },
    ],
    tips: ['Password-protect family-only content.', 'Update event calendars without reprinting.'],
    landingPage: { enabled: true, template: 'minimal', title: 'Welcome', accentColor: '#9333ea', ctaLabel: 'Continue' },
  },
  {
    id: 'mobile-vendor',
    name: 'Mobile Vendor',
    category: 'menu',
    tagline: 'Food trucks and pop-ups — menu and orders on the go',
    description: 'Rotating locations with one printed QR.',
    useCases: ['Truck window', 'Festival booth', 'Social bio'],
    suggestedQrName: 'Today\'s Menu',
    qrData: { url: 'https://yourtruck.com/menu', _truckName: '', _location: '' },
    style: {
      fgColor: '#c2410c',
      bgColor: '#fff7ed',
      dotStyle: 'rounded',
      frameStyle: 'sticker',
      frameColor: '#c2410c',
      frameText: 'ORDER',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'menu',
        title: 'Menu or order link',
        description: 'Daily menu, mobile ordering or location updates.',
        fields: [
          { key: 'url', label: 'Menu URL', required: true, type: 'url' },
          { key: '_truckName', label: 'Vendor name', type: 'text' },
          { key: '_location', label: 'Today\'s location', type: 'text' },
        ],
      },
    ],
    tips: ['Update daily location on landing page.', 'Same QR on truck all season.'],
    landingPage: { enabled: true, template: 'restaurant', title: 'Today\'s Menu', accentColor: '#c2410c', ctaLabel: 'Order' },
  },
  {
    id: 'local-services-hub',
    name: 'Local Services',
    category: 'url',
    tagline: 'Booking, intake and promos for neighborhood businesses',
    description: 'Grooming, laundry, printing, landscaping and more.',
    useCases: ['Storefront', 'Vehicle decal', 'Counter card', 'Yard sign'],
    suggestedQrName: 'Book Service',
    qrData: { url: 'https://yourbusiness.com/book', _businessName: '', _offer: '' },
    style: {
      fgColor: '#ea580c',
      bgColor: '#fff7ed',
      dotStyle: 'square',
      frameStyle: 'scan-me',
      frameColor: '#ea580c',
      frameText: 'BOOK NOW',
      errorCorrection: 'H',
      margin: 8,
    },
    sections: [
      {
        id: 'booking',
        title: 'Service link',
        description: 'Online booking, quote request or service promo.',
        fields: [
          { key: 'url', label: 'Booking URL', required: true, type: 'url' },
          { key: '_businessName', label: 'Business name', type: 'text' },
          { key: '_offer', label: 'Current offer', type: 'text' },
        ],
      },
    ],
    tips: ['Seasonal promo swaps on same truck decal.', 'Lead form on landing page.'],
    landingPage: {
      enabled: true,
      template: 'business',
      title: 'Book a Service',
      accentColor: '#ea580c',
      ctaLabel: 'Book Now',
      leadFormEnabled: true,
      leadForm: { collectName: true, collectPhone: true, requiredEmail: false },
    },
  },
];
