import type { AdvancedValues } from '@/components/qr/advanced-settings';
import type { LandingPageData } from '@/components/qr/landing-page-editor';
import type { ScheduleData } from '@/components/qr/schedule-settings';
import type { GeofenceData } from '@/components/qr/geofence-settings';
import type { AbTestData } from '@/lib/ab-routing';
import type { ScanNotifyValues } from '@/components/qr/scan-notify-settings';
import type { PixelAnalyticsConfig } from '@/components/qr/analytics-pixel-settings';
import type { QRStyleConfig } from '@/lib/qr-style';
import type { IndustryTemplate } from '@/lib/industry-templates';

export type QrCreateStepDesignProps = {
  category: string;
  name: string;
  qrData: Record<string, string>;
  style: QRStyleConfig;
  logoPreview: string | null;
  activeTemplate: IndustryTemplate | null;
  landingPage: LandingPageData;
  advanced: AdvancedValues;
  landingEnabled: boolean;
  scheduleEnabled: boolean;
  scheduleData: ScheduleData;
  geofenceEnabled: boolean;
  geofenceData: GeofenceData;
  abTestEnabled: boolean;
  abTestData: AbTestData;
  gpsHeatmapEnabled: boolean;
  scanNotify: ScanNotifyValues;
  pixels: PixelAnalyticsConfig;
  contentLength: number;
  onStyleChange: (style: QRStyleConfig) => void;
  canUndoStyle?: boolean;
  canRedoStyle?: boolean;
  onUndoStyle?: () => void;
  onRedoStyle?: () => void;
  onLogoChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  logoPath?: string | null;
  onTemplateLogoApply?: (path: string | null) => void;
  onAdvancedChange: (values: AdvancedValues) => void;
  onLandingEnabledChange: (enabled: boolean) => void;
  onLandingPageChange: (data: LandingPageData) => void;
  onScheduleEnabledChange: (enabled: boolean) => void;
  onScheduleDataChange: (data: ScheduleData) => void;
  onGeofenceEnabledChange: (enabled: boolean) => void;
  onGeofenceDataChange: (data: GeofenceData) => void;
  onAbTestEnabledChange: (enabled: boolean) => void;
  onAbTestDataChange: (data: AbTestData) => void;
  onGpsHeatmapEnabledChange: (enabled: boolean) => void;
  onScanNotifyChange: (values: ScanNotifyValues) => void;
  onPixelsChange: (values: PixelAnalyticsConfig) => void;
};
