import { resolveQrContentLength } from '@/lib/qr-preview-content';
import type { QrCreateFormState } from '@/hooks/use-qr-create-form';
import type { QrCreateStepDesignProps } from '@/lib/qr-create-step-design-types';

export function mapQrCreateDesignStepProps(
  form: QrCreateFormState,
  scanBaseUrl: string,
): QrCreateStepDesignProps {
  const {
    category,
    name,
    qrData,
    style,
    logoPreview,
    storedLogoPath,
    activeTemplate,
    landingPage,
    advanced,
    landingEnabled,
    scheduleEnabled,
    scheduleData,
    geofenceEnabled,
    geofenceData,
    languageRedirectEnabled,
    languageRedirectData,
    abTestEnabled,
    abTestData,
    gpsHeatmapEnabled,
    scanNotify,
    pixels,
    payloadData,
    setStyle,
    canUndoStyle,
    canRedoStyle,
    undoStyle,
    redoStyle,
    handleLogoChange,
    applyTemplateLogo,
    setAdvanced,
    setLandingEnabled,
    setLandingPage,
    setScheduleEnabled,
    setScheduleData,
    setGeofenceEnabled,
    setGeofenceData,
    setLanguageRedirectEnabled,
    setLanguageRedirectData,
    setAbTestEnabled,
    setAbTestData,
    setGpsHeatmapEnabled,
    setScanNotify,
    setPixels,
  } = form;

  return {
    category,
    name,
    qrData,
    style,
    logoPreview,
    activeTemplate,
    landingPage,
    advanced,
    landingEnabled,
    scheduleEnabled,
    scheduleData,
    geofenceEnabled,
    geofenceData,
    languageRedirectEnabled,
    languageRedirectData,
    abTestEnabled,
    abTestData,
    gpsHeatmapEnabled,
    scanNotify,
    pixels,
    contentLength: resolveQrContentLength(category, payloadData(), undefined, scanBaseUrl),
    onStyleChange: setStyle,
    canUndoStyle,
    canRedoStyle,
    onUndoStyle: undoStyle,
    onRedoStyle: redoStyle,
    onLogoChange: handleLogoChange,
    logoPath: storedLogoPath,
    onTemplateLogoApply: applyTemplateLogo,
    onAdvancedChange: setAdvanced,
    onLandingEnabledChange: setLandingEnabled,
    onLandingPageChange: setLandingPage,
    onScheduleEnabledChange: setScheduleEnabled,
    onScheduleDataChange: setScheduleData,
    onGeofenceEnabledChange: setGeofenceEnabled,
    onGeofenceDataChange: setGeofenceData,
    onLanguageRedirectEnabledChange: setLanguageRedirectEnabled,
    onLanguageRedirectDataChange: setLanguageRedirectData,
    onAbTestEnabledChange: setAbTestEnabled,
    onAbTestDataChange: setAbTestData,
    onGpsHeatmapEnabledChange: setGpsHeatmapEnabled,
    onScanNotifyChange: setScanNotify,
    onPixelsChange: setPixels,
  };
}
