import {
  Utensils,
  IdCard,
  Wifi,
  PartyPopper,
  Store,
  Hotel,
  HeartPulse,
  Landmark,
  Megaphone,
  Building2,
  GraduationCap,
  Trophy,
  ShoppingCart,
  Film,
  Truck,
  Car,
  Dumbbell,
  Sparkles,
  Heart,
  Beer,
  Shield,
  Smile,
  PawPrint,
  Scale,
  Calculator,
  Eye,
  Baby,
  Wrench,
  HeartHandshake,
  Scissors,
  Briefcase,
  Music,
  Wheat,
  Wine,
  Anchor,
  UserPlus,
  Coffee,
  Ticket,
  MapPin,
  Flower2,
  Cake,
  SprayCan,
  UtensilsCrossed,
  Trees,
  Shirt,
  Church,
  Printer,
  BookOpen,
  type LucideIcon,
} from 'lucide-react';

export const SOLUTION_ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  'id-card': IdCard,
  wifi: Wifi,
  'party-popper': PartyPopper,
  store: Store,
  hotel: Hotel,
  'heart-pulse': HeartPulse,
  landmark: Landmark,
  megaphone: Megaphone,
  building: Building2,
  'graduation-cap': GraduationCap,
  trophy: Trophy,
  'shopping-cart': ShoppingCart,
  film: Film,
  truck: Truck,
  car: Car,
  dumbbell: Dumbbell,
  sparkles: Sparkles,
  heart: Heart,
  beer: Beer,
  shield: Shield,
  smile: Smile,
  'paw-print': PawPrint,
  scale: Scale,
  calculator: Calculator,
  eye: Eye,
  baby: Baby,
  wrench: Wrench,
  'heart-handshake': HeartHandshake,
  scissors: Scissors,
  briefcase: Briefcase,
  music: Music,
  wheat: Wheat,
  wine: Wine,
  anchor: Anchor,
  'user-plus': UserPlus,
  coffee: Coffee,
  ticket: Ticket,
  'map-pin': MapPin,
  flower: Flower2,
  cake: Cake,
  'spray-can': SprayCan,
  'utensils-crossed': UtensilsCrossed,
  trees: Trees,
  shirt: Shirt,
  church: Church,
  printer: Printer,
  'book-open': BookOpen,
};

export function solutionIcon(key: string): LucideIcon {
  return SOLUTION_ICON_MAP[key] ?? Utensils;
}
