import type { QRStyleConfig } from '@/lib/qr-style';
import { applyTemplateStyleStandards } from '@/lib/template-design-standards';

export type VisualPresetCategory =
  | 'business'
  | 'hospitality'
  | 'retail'
  | 'social'
  | 'event'
  | 'health'
  | 'minimal'
  | 'luxury';

export interface VisualQRPreset {
  id: string;
  name: string;
  category: VisualPresetCategory;
  description: string;
  sectors: string[];
  designStyle: 'modern' | 'luxury' | 'minimal' | 'corporate' | 'organic' | 'tech' | 'premium';
  ctaDefault: string;
  style: Partial<QRStyleConfig>;
}

const base = (style: Partial<QRStyleConfig>): Partial<QRStyleConfig> =>
  applyTemplateStyleStandards({
    errorCorrection: 'H',
    margin: 8,
    ...style,
  });

export const VISUAL_QR_PRESETS: VisualQRPreset[] = [
  {
    id: 'modern-business',
    name: 'Modern Business',
    category: 'business',
    description: 'Clean corporate look for cards, offices and B2B collateral.',
    sectors: ['Business Card', 'Corporate', 'Office', 'Agency'],
    designStyle: 'corporate',
    ctaDefault: 'Contact Us',
    style: base({
      fgColor: '#1e293b',
      bgColor: '#ffffff',
      dotStyle: 'classy',
      cornerStyle: 'classy',
      frameStyle: 'rounded',
      frameColor: '#1e293b',
      frameText: 'SCAN ME',
    }),
  },
  {
    id: 'luxury-black',
    name: 'Luxury Black',
    category: 'luxury',
    description: 'Premium dark palette for high-end brands and galas.',
    sectors: ['Luxury', 'Event', 'Hotel', 'Retail'],
    designStyle: 'luxury',
    ctaDefault: 'Discover',
    style: base({
      fgColor: '#f8fafc',
      bgColor: '#0f172a',
      dotStyle: 'classy-rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'shadow',
      frameColor: '#1e293b',
      frameText: 'SCAN ME',
      frameTextColor: '#f8fafc',
      backgroundGradientEnabled: true,
      backgroundGradientColor2: '#1e293b',
    }),
  },
  {
    id: 'restaurant-elegant',
    name: 'Restaurant Elegant',
    category: 'hospitality',
    description: 'Warm amber tones for menus and table tents.',
    sectors: ['Restaurant', 'Cafe', 'Table Menu', 'Hotel'],
    designStyle: 'organic',
    ctaDefault: 'View Menu',
    style: base({
      fgColor: '#b45309',
      bgColor: '#fffbeb',
      dotStyle: 'rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'badge',
      frameColor: '#b45309',
      frameText: 'VIEW MENU',
      gradientEnabled: true,
      gradientColor2: '#f59e0b',
    }),
  },
  {
    id: 'cafe-warm',
    name: 'Café Warm',
    category: 'hospitality',
    description: 'Roasted coffee palette for counters and loyalty cards.',
    sectors: ['Cafe', 'Coffee Shop', 'Table Card'],
    designStyle: 'organic',
    ctaDefault: 'Order Now',
    style: base({
      fgColor: '#92400e',
      bgColor: '#fffbeb',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'badge',
      frameColor: '#92400e',
      frameText: 'ORDER',
      gradientEnabled: true,
      gradientColor2: '#d97706',
    }),
  },
  {
    id: 'hotel-hospitality',
    name: 'Hotel Premium',
    category: 'hospitality',
    description: 'Elegant blue for guest hubs and room collateral.',
    sectors: ['Hotel', 'Spa', 'Resort', 'Reception'],
    designStyle: 'premium',
    ctaDefault: 'Guest Info',
    style: base({
      fgColor: '#1e40af',
      bgColor: '#eff6ff',
      dotStyle: 'classy-rounded',
      cornerStyle: 'classy-rounded',
      frameStyle: 'badge',
      frameColor: '#1e40af',
      frameText: 'GUEST INFO',
      gradientEnabled: true,
      gradientColor2: '#3b82f6',
    }),
  },
  {
    id: 'event-ticket',
    name: 'Event Ticket',
    category: 'event',
    description: 'Bold indigo for registrations, conferences and festivals.',
    sectors: ['Event', 'Conference', 'Exhibition', 'Poster'],
    designStyle: 'modern',
    ctaDefault: 'Register',
    style: base({
      fgColor: '#4f46e5',
      bgColor: '#eef2ff',
      dotStyle: 'rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'scan-me',
      frameColor: '#4f46e5',
      frameText: 'REGISTER',
      gradientEnabled: true,
      gradientColor2: '#6366f1',
    }),
  },
  {
    id: 'wedding-gold',
    name: 'Wedding Gold',
    category: 'event',
    description: 'Romantic rose and blush for invitations and table cards.',
    sectors: ['Wedding', 'Invitation', 'Celebration'],
    designStyle: 'luxury',
    ctaDefault: 'RSVP',
    style: base({
      fgColor: '#9d174d',
      bgColor: '#fdf2f8',
      dotStyle: 'classy-rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'badge',
      frameColor: '#9d174d',
      frameText: 'OPEN INVITE',
      gradientEnabled: true,
      gradientColor2: '#f472b6',
    }),
  },
  {
    id: 'real-estate-premium',
    name: 'Real Estate Premium',
    category: 'business',
    description: 'Trust-building green for listings and yard signs.',
    sectors: ['Real Estate', 'Construction', 'Open House'],
    designStyle: 'corporate',
    ctaDefault: 'View Listing',
    style: base({
      fgColor: '#166534',
      bgColor: '#f0fdf4',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'scan-me',
      frameColor: '#166534',
      frameText: 'VIEW HOME',
      gradientEnabled: true,
      gradientColor2: '#22c55e',
    }),
  },
  {
    id: 'instagram-growth',
    name: 'Instagram Growth',
    category: 'social',
    description: 'Vibrant magenta gradient for packaging and retail.',
    sectors: ['Instagram', 'Retail', 'E-commerce', 'Sticker'],
    designStyle: 'premium',
    ctaDefault: 'Follow Us',
    style: base({
      fgColor: '#db2777',
      bgColor: '#ffffff',
      dotStyle: 'rounded',
      cornerStyle: 'dot',
      frameStyle: 'badge',
      frameColor: '#db2777',
      frameText: 'FOLLOW US',
      gradientEnabled: true,
      gradientColor2: '#f472b6',
      gradientRotation: 135,
    }),
  },
  {
    id: 'youtube-red',
    name: 'YouTube Channel',
    category: 'social',
    description: 'Classic red subscribe CTA for video and merch.',
    sectors: ['YouTube', 'Video', 'Education', 'Creator'],
    designStyle: 'modern',
    ctaDefault: 'Subscribe',
    style: base({
      fgColor: '#dc2626',
      bgColor: '#ffffff',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'badge',
      frameColor: '#dc2626',
      frameText: 'SUBSCRIBE',
    }),
  },
  {
    id: 'whatsapp-contact',
    name: 'WhatsApp Contact',
    category: 'social',
    description: 'Recognizable green for chat and support flows.',
    sectors: ['WhatsApp', 'Support', 'Retail', 'Service'],
    designStyle: 'tech',
    ctaDefault: 'Start Chat',
    style: base({
      fgColor: '#15803d',
      bgColor: '#f0fdf4',
      dotStyle: 'rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'badge',
      frameColor: '#15803d',
      frameText: 'CHAT NOW',
    }),
  },
  {
    id: 'product-label',
    name: 'Product Label',
    category: 'retail',
    description: 'Shelf-ready purple for packaging and promotions.',
    sectors: ['Retail', 'Product Packaging', 'Label', 'Sticker'],
    designStyle: 'modern',
    ctaDefault: 'Shop Now',
    style: base({
      fgColor: '#7c3aed',
      bgColor: '#faf5ff',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'sticker',
      frameColor: '#7c3aed',
      frameText: 'SHOP NOW',
      gradientEnabled: true,
      gradientColor2: '#a78bfa',
    }),
  },
  {
    id: 'menu-premium',
    name: 'Menu Premium',
    category: 'hospitality',
    description: 'High-contrast menu style for dim dining rooms.',
    sectors: ['Restaurant', 'Bar', 'Digital Menu'],
    designStyle: 'premium',
    ctaDefault: 'View Menu',
    style: base({
      fgColor: '#fafafa',
      bgColor: '#18181b',
      dotStyle: 'extra-rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'badge',
      frameColor: '#27272a',
      frameText: 'VIEW MENU',
      frameTextColor: '#fafafa',
    }),
  },
  {
    id: 'healthcare-clean',
    name: 'Healthcare Clean',
    category: 'health',
    description: 'Calm teal for clinics and patient education.',
    sectors: ['Healthcare', 'Clinic', 'Doctor', 'Dental'],
    designStyle: 'minimal',
    ctaDefault: 'Patient Portal',
    style: base({
      fgColor: '#0d9488',
      bgColor: '#f0fdfa',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'badge',
      frameColor: '#0d9488',
      frameText: 'PATIENT INFO',
    }),
  },
  {
    id: 'dental-fresh',
    name: 'Dental Fresh',
    category: 'health',
    description: 'Fresh cyan for dental practices and chairside cards.',
    sectors: ['Dentist', 'Healthcare', 'Office'],
    designStyle: 'tech',
    ctaDefault: 'Book Now',
    style: base({
      fgColor: '#0891b2',
      bgColor: '#ecfeff',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'badge',
      frameColor: '#0891b2',
      frameText: 'PATIENT CARE',
    }),
  },
  {
    id: 'museum-classic',
    name: 'Museum Classic',
    category: 'retail',
    description: 'Earthy bronze for exhibits and gallery labels.',
    sectors: ['Museum', 'Exhibition', 'Gallery', 'Venue'],
    designStyle: 'organic',
    ctaDefault: 'Learn More',
    style: base({
      fgColor: '#78350f',
      bgColor: '#fffbeb',
      dotStyle: 'square',
      cornerStyle: 'square',
      frameStyle: 'scan-me',
      frameColor: '#78350f',
      frameText: 'LEARN MORE',
    }),
  },
  {
    id: 'fitness-energy',
    name: 'Fitness Energy',
    category: 'retail',
    description: 'High-energy red-orange for gyms and studios.',
    sectors: ['Fitness', 'Gym', 'Sports', 'Poster'],
    designStyle: 'modern',
    ctaDefault: 'Join Now',
    style: base({
      fgColor: '#dc2626',
      bgColor: '#fef2f2',
      dotStyle: 'rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'badge',
      frameColor: '#dc2626',
      frameText: 'JOIN NOW',
      gradientEnabled: true,
      gradientColor2: '#f97316',
    }),
  },
  {
    id: 'salon-rose',
    name: 'Salon Rose',
    category: 'retail',
    description: 'Soft pink for salons, spas and beauty retail.',
    sectors: ['Salon', 'Spa', 'Beauty', 'Nail Salon'],
    designStyle: 'luxury',
    ctaDefault: 'Book Now',
    style: base({
      fgColor: '#be185d',
      bgColor: '#fdf2f8',
      dotStyle: 'extra-rounded',
      cornerStyle: 'extra-rounded',
      frameStyle: 'rounded',
      frameColor: '#be185d',
      frameText: 'BOOK NOW',
    }),
  },
  {
    id: 'nonprofit-heart',
    name: 'Nonprofit Heart',
    category: 'event',
    description: 'Warm red for donations and volunteer drives.',
    sectors: ['Nonprofit', 'Charity', 'Fundraising', 'Gala'],
    designStyle: 'organic',
    ctaDefault: 'Donate',
    style: base({
      fgColor: '#b91c1c',
      bgColor: '#fef2f2',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'coupon',
      frameColor: '#b91c1c',
      frameText: 'DONATE',
      backgroundGradientEnabled: true,
      backgroundGradientColor2: '#fff1f2',
    }),
  },
  {
    id: 'home-services-bold',
    name: 'Home Services',
    category: 'business',
    description: 'Bold orange for trucks, yard signs and contractors.',
    sectors: ['HVAC', 'Plumber', 'Contractor', 'Vehicle'],
    designStyle: 'corporate',
    ctaDefault: 'Get Quote',
    style: base({
      fgColor: '#ea580c',
      bgColor: '#fff7ed',
      dotStyle: 'square',
      cornerStyle: 'square',
      frameStyle: 'scan-me',
      frameColor: '#ea580c',
      frameText: 'GET QUOTE',
    }),
  },
  {
    id: 'tourist-green',
    name: 'Tourist Guide',
    category: 'retail',
    description: 'Nature green for attractions, parks and landmarks.',
    sectors: ['Tourist Attraction', 'Park', 'Landmark', 'Museum'],
    designStyle: 'organic',
    ctaDefault: 'Get Tickets',
    style: base({
      fgColor: '#15803d',
      bgColor: '#f0fdf4',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'scan-me',
      frameColor: '#15803d',
      frameText: 'VISITOR INFO',
      gradientEnabled: true,
      gradientColor2: '#22c55e',
    }),
  },
  {
    id: 'corporate-navy',
    name: 'Corporate Navy',
    category: 'business',
    description: 'Trustworthy navy for enterprise and finance.',
    sectors: ['Corporate', 'Finance', 'Lawyer', 'Startup'],
    designStyle: 'corporate',
    ctaDefault: 'Learn More',
    style: base({
      fgColor: '#1e3a8a',
      bgColor: '#eff6ff',
      dotStyle: 'classy',
      cornerStyle: 'classy',
      frameStyle: 'double',
      frameColor: '#1e3a8a',
      frameText: 'SCAN ME',
    }),
  },
  {
    id: 'startup-indigo',
    name: 'Startup Indigo',
    category: 'business',
    description: 'Tech-forward indigo for SaaS and product launches.',
    sectors: ['Startup', 'SaaS', 'Agency', 'Portfolio'],
    designStyle: 'tech',
    ctaDefault: 'Open Website',
    style: base({
      fgColor: '#4f46e5',
      bgColor: '#ffffff',
      dotStyle: 'classy',
      cornerStyle: 'classy',
      frameStyle: 'badge',
      frameColor: '#4f46e5',
      frameText: 'SCAN ME',
      gradientEnabled: true,
      gradientColor2: '#7c3aed',
    }),
  },
  {
    id: 'minimal-mono',
    name: 'Minimal Mono',
    category: 'minimal',
    description: 'Ultra-clean black on white for maximum scan reliability.',
    sectors: ['Minimal', 'Invoice', 'Document', 'Office'],
    designStyle: 'minimal',
    ctaDefault: 'Scan Me',
    style: base({
      fgColor: '#000000',
      bgColor: '#ffffff',
      dotStyle: 'square',
      cornerStyle: 'square',
      frameStyle: 'none',
      margin: 10,
    }),
  },
  {
    id: 'wifi-blue',
    name: 'Wi‑Fi Connect',
    category: 'minimal',
    description: 'Clear blue for guest network signs.',
    sectors: ['Wifi', 'Hotel', 'Cafe', 'Office'],
    designStyle: 'tech',
    ctaDefault: 'Connect WiFi',
    style: base({
      fgColor: '#0369a1',
      bgColor: '#f0f9ff',
      dotStyle: 'rounded',
      cornerStyle: 'rounded',
      frameStyle: 'badge',
      frameColor: '#0369a1',
      frameText: 'JOIN Wi‑Fi',
    }),
  },
  {
    id: 'crypto-gold',
    name: 'Crypto Donate',
    category: 'luxury',
    description: 'Gold on dark for tips and crypto donations.',
    sectors: ['Payment', 'Crypto', 'Donation', 'Creator'],
    designStyle: 'luxury',
    ctaDefault: 'Donate',
    style: base({
      fgColor: '#f59e0b',
      bgColor: '#0f172a',
      dotStyle: 'square',
      cornerStyle: 'square',
      frameStyle: 'badge',
      frameColor: '#1e293b',
      frameText: 'DONATE',
      frameTextColor: '#f59e0b',
    }),
  },
  {
    id: 'cv-professional',
    name: 'CV Professional',
    category: 'business',
    description: 'Professional blue for resumes and job fairs.',
    sectors: ['Resume', 'Recruitment', 'Education', 'Career'],
    designStyle: 'corporate',
    ctaDefault: 'Download PDF',
    style: base({
      fgColor: '#0369a1',
      bgColor: '#ffffff',
      dotStyle: 'square',
      cornerStyle: 'square',
      frameStyle: 'badge',
      frameColor: '#0369a1',
      frameText: 'MY CV',
    }),
  },
];

export const VISUAL_PRESET_CATEGORIES: {
  id: VisualPresetCategory;
  label: string;
}[] = [
  { id: 'business', label: 'Business & Corporate' },
  { id: 'hospitality', label: 'Restaurant & Hotel' },
  { id: 'retail', label: 'Retail & Venue' },
  { id: 'social', label: 'Social & Chat' },
  { id: 'event', label: 'Events & Nonprofit' },
  { id: 'health', label: 'Healthcare' },
  { id: 'minimal', label: 'Minimal & Wi‑Fi' },
  { id: 'luxury', label: 'Luxury & Premium' },
];

export const INDUSTRY_VISUAL_PRESET_MAP: Record<string, string> = {
  'restaurant-menu': 'restaurant-elegant',
  'business-card': 'modern-business',
  wedding: 'wedding-gold',
  'event-registration': 'event-ticket',
  'instagram-bio': 'instagram-growth',
  'youtube-channel': 'youtube-red',
  portfolio: 'startup-indigo',
  'cv-resume': 'cv-professional',
  'crypto-donate': 'crypto-gold',
  'real-estate': 'real-estate-premium',
  'wifi-guest': 'wifi-blue',
  'retail-stores': 'product-label',
  'hotels-hospitality': 'hotel-hospitality',
  'healthcare-clinics': 'healthcare-clean',
  'museums-venues': 'museum-classic',
  'fitness-gyms': 'fitness-energy',
  'salon-spa': 'salon-rose',
  'nonprofit-fundraising': 'nonprofit-heart',
  'dental-clinics': 'dental-fresh',
  'home-services': 'home-services-bold',
  'coffee-shops-cafes': 'cafe-warm',
  'tourist-attractions': 'tourist-green',
  'campus-institution': 'corporate-navy',
  'professional-services': 'modern-business',
  'retail-grocery': 'product-label',
  'entertainment-venue': 'event-ticket',
  'automotive-marine': 'real-estate-premium',
  'property-facilities': 'real-estate-premium',
  'specialty-healthcare': 'dental-fresh',
  'family-community': 'nonprofit-heart',
  'mobile-vendor': 'cafe-warm',
  'local-services-hub': 'home-services-bold',
};

export function getVisualPresetById(id: string): VisualQRPreset | undefined {
  return VISUAL_QR_PRESETS.find((p) => p.id === id);
}

export function getVisualPresetForIndustry(industryTemplateId: string): VisualQRPreset | undefined {
  const presetId = INDUSTRY_VISUAL_PRESET_MAP[industryTemplateId];
  return presetId ? getVisualPresetById(presetId) : undefined;
}

export function mergeIndustryVisualStyle(
  industryTemplateId: string,
  industryStyle: Partial<QRStyleConfig>
): Partial<QRStyleConfig> {
  const preset = getVisualPresetForIndustry(industryTemplateId);
  if (!preset) return applyTemplateStyleStandards(industryStyle);
  return applyTemplateStyleStandards({
    ...preset.style,
    ...industryStyle,
    frameText: industryStyle.frameText ?? preset.style.frameText,
  });
}
